.TH LIBJ2_J2I_MAX_J2I 3 LIBJ2
.SH NAME
libj2_j2i_max_j2i \- Select maximum of two values

.SH SYNOPSIS
.nf
#include <libj2.h>

void \fBlibj2_j2i_max_j2i\fP(struct libj2_j2i *\fIa\fP, const struct libj2_j2i *\fIb\fP);
void \fBlibj2_j2i_max_j2i_to_j2i\fP(const struct libj2_j2i *\fIa\fP, const struct libj2_j2i *\fIb\fP, struct libj2_j2i *\fIr\fP);
void \fBlibj2_j2i_max_ji\fP(struct libj2_j2i *\fIa\fP, intmax_t \fIb\fP);
void \fBlibj2_j2i_max_ji_to_j2i\fP(const struct libj2_j2i *\fIa\fP, intmax_t \fIb\fP, struct libj2_j2i *\fIr\fP);
void \fBlibj2_j2u_max_j2u\fP(struct libj2_j2u *\fIa\fP, const struct libj2_j2u *\fIb\fP);
void \fBlibj2_j2u_max_j2u_to_j2u\fP(const struct libj2_j2u *\fIa\fP, const struct libj2_j2u *\fIb\fP, struct libj2_j2u *\fIr\fP);
void \fBlibj2_j2u_max_ju\fP(struct libj2_j2u *\fIa\fP, uintmax_t \fIb\fP);
void \fBlibj2_j2u_max_ju_to_j2u\fP(const struct libj2_j2u *\fIa\fP, uintmax_t \fIb\fP, struct libj2_j2u *\fIr\fP);
.fi
.PP
Link with
.IR -lj2 .

.SH DESCRIPTION
The above listed functions
selects the maximum value of
.I a
and
.I b
and stores the result in
.IR r ,
or in
.I a
for the functions that does not have an
.I r
parameter.
.PP
The arguments are assumed to be
.RI non- NULL .

.SH RETURN VALUE
None.

.SH ERRORS
The above listed functions cannot fail.

.SH HISTORY
The
.BR libj2_j2u_max_j2u (),
.BR libj2_j2u_max_j2u_to_j2u (),
.BR libj2_j2u_max_ju (),
and
.BR libj2_j2u_max_ju_to_j2u ()
functions were added in version 1.0 of
.BR libj2 .
.PP
The
.BR libj2_j2i_max_j2i (),
.BR libj2_j2i_max_j2i_to_j2i (),
.BR libj2_j2i_max_ji (),
and
.BR libj2_j2i_max_ji_to_j2i ()
functions were added in version 1.1 of
.BR libj2 .

.SH SEE ALSO
.BR libj2 (7),
.BR libj2_j2i_min_j2i (3),
.BR libj2_max_j2i (3),
.BR libj2_min_j2i (3)
