.TH LIBJ2_J2I_CMP_J2I 3 LIBJ2
.SH NAME
libj2_j2i_cmp_j2i \- Compare two values

.SH SYNOPSIS
.nf
#include <libj2.h>

int \fBlibj2_j2i_cmp_j2i\fP(const struct libj2_j2i *\fIa\fP, const struct libj2_j2i *\fIb\fP);
int \fBlibj2_j2i_cmp_ji\fP(const struct libj2_j2i *\fIa\fP, intmax_t \fIb\fP);
int \fBlibj2_ji_cmp_j2i\fP(intmax_t \fIa\fP, const struct libj2_j2i *\fIb\fP);
int \fBlibj2_j2i_cmp_j2u\fP(const struct libj2_j2i *\fIa\fP, const struct libj2_j2u *\fIb\fP);
int \fBlibj2_j2i_cmp_ju\fP(const struct libj2_j2i *\fIa\fP, uintmax_t \fIb\fP);
int \fBlibj2_ji_cmp_j2u\fP(intmax_t \fIa\fP, const struct libj2_j2u *\fIb\fP);
int \fBlibj2_j2u_cmp_j2i\fP(const struct libj2_j2u *\fIa\fP, const struct libj2_j2i *\fIb\fP);
int \fBlibj2_j2u_cmp_ji\fP(const struct libj2_j2u *\fIa\fP, intmax_t \fIb\fP);
int \fBlibj2_ju_cmp_j2i\fP(uintmax_t \fIa\fP, const struct libj2_j2i *\fIb\fP);
int \fBlibj2_j2u_cmp_j2u\fP(const struct libj2_j2u *\fIa\fP, const struct libj2_j2u *\fIb\fP);
int \fBlibj2_j2u_cmp_ju\fP(const struct libj2_j2u *\fIa\fP, uintmax_t \fIb\fP);
int \fBlibj2_ju_cmp_j2u\fP(uintmax_t \fIa\fP, const struct libj2_j2u *\fIb\fP);
.fi
.PP
Link with
.IR -lj2 .

.SH DESCRIPTION
The above listed functions return compare the of
.I a
to the value of
.IR b ,
and return the signum of the difference
between
.I a
and
.IR b .
.PP
The arguments are assumed to be
.RI non- NULL .

.SH RETURN VALUE
The functions return -1 if
.I a
is less than
.IR b ,
+1 if
.I a
is greater than
.IR b ,
and 0 if
.I a
and
.I b
are equals.

.SH ERRORS
The functions cannot fail.

.SH HISTORY
The
.BR libj2_j2u_cmp_j2u (),
.BR libj2_j2u_cmp_ju (),
and
.BR libj2_ju_cmp_j2u ()
functions were added in version 1.0 of
.BR libj2 .
.PP
The
.BR libj2_j2i_cmp_j2i (),
.BR libj2_j2i_cmp_ji (),
.BR libj2_ji_cmp_j2i (),
.BR libj2_j2i_cmp_j2u (),
.BR libj2_j2i_cmp_ju (),
.BR libj2_ji_cmp_j2u (),
.BR libj2_j2u_cmp_j2i (),
.BR libj2_j2u_cmp_ji (),
and
.BR libj2_ju_cmp_j2i ()
functions were added in version 1.1 of
.BR libj2 .

.SH SEE ALSO
.BR libj2 (7),
.BR libj2_j2i_eq_j2i (3),
.BR libj2_j2i_ne_j2i (3),
.BR libj2_j2i_lt_j2i (3),
.BR libj2_j2i_le_j2i (3),
.BR libj2_j2i_gt_j2i (3),
.BR libj2_j2i_ge_j2i (3)
