.TH LIBJ2_KLS_J2U 3 LIBJ2
.SH NAME
libj2_kls_j2u \- Keep last set bit, clear the rest

.SH SYNOPSIS
.nf
#include <libj2.h>

void \fBlibj2_kls_j2u\fP(struct libj2_j2u *\fIa\fP);
void \fBlibj2_kls_j2u_to_j2u\fP(const struct libj2_j2u *\fIa\fP, struct libj2_j2u *\fIr\fP);
.fi
.PP
Link with
.IR -lj2 .

.SH DESCRIPTION
The
.BR libj2_kls_j2u ()
function clears all bits in
.I a
except the last (most significant)
set bit (no modification if all bits
are cleared).
.PP
The
.BR libj2_kls_j2u_to_j2u ()
function performs the same action as
.BR libj2_kls_j2u ()
but instead of modifying
.IR a ,
the result is stored in
.IR r .
.PP
The arguments are assumed to be
.RI non- NULL .

.SH RETURN VALUE
None.

.SH ERRORS
The
.BR libj2_kls_j2u ()
and
.BR libj2_kls_j2u_to_j2u ()
functions cannot fail.

.SH SEE ALSO
.BR libj2 (7),
.BR libj2_kfs_j2u (3),
.BR libj2_fls_j2u (3),
.BR libj2_cls_j2u (3),
.BR libj2_slc_j2u (3)
